import * as Crypto from "expo-crypto";

/**
 * Single shared entry point for every UUID generated by the app. Every call
 * site must check for an existing stored value before calling this and
 * persist the result immediately, so the same entity never gets a new uuid
 * on a later pass (project_uuid, custom protocol uuid, catalog row uuids).
 */
export function generateUuid(): string {
  return Crypto.randomUUID();
}
