import type { ModuleSchema, FieldSchema, SelectOption } from "@/protocol-kernel/types";

// --- Geomorphology and Relief ---

// Exported so other services (e.g. landscape name generation) can translate
// a stored geomorphology_type value back to its label instead of duplicating
// these translations.
export const geomorphologyTypeOptions: SelectOption[] = [
  {
    value: "hillslope",
    label: { pt: "De encosta", en: "Hillslope", es: "De ladera", fr: "En versant" },
    desc: { pt: "Superfícies inclinadas moldadas por processos de intemperismo, erosão e movimentos de massa", en: "Inclined surfaces shaped by weathering, erosion and mass movement processes", es: "Superficies inclinadas moldeadas por procesos de meteorización, erosión y movimientos en masa", fr: "Surfaces inclinées façonnées par l'altération, l'érosion et les mouvements de masse" },
  },
  {
    value: "fluvial",
    label: { pt: "Fluvial", en: "Fluvial", es: "Fluvial", fr: "Fluvial" },
    desc: { pt: "Formas criadas pela ação de rios e córregos: planícies de inundação, terraços, calhas aluviais", en: "Forms created by river and stream action: floodplains, terraces, alluvial channels", es: "Formas creadas por la acción de ríos y arroyos: llanuras de inundación, terrazas, cauces aluviales", fr: "Formes créées par l'action des cours d'eau : plaines inondables, terrasses, chenaux alluviaux" },
  },
  {
    value: "lacustrine",
    label: { pt: "Lacustre", en: "Lacustrine", es: "Lacustre", fr: "Lacustre" },
    desc: { pt: "Ambientes associados a lagos e lagoas; depósitos de fundo e margens lacustres", en: "Environments associated with lakes and ponds; bottom deposits and lacustrine margins", es: "Ambientes asociados a lagos y lagunas; depósitos de fondo y márgenes lacustres", fr: "Environnements associés aux lacs et étangs ; dépôts de fond et rives lacustres" },
  },
  {
    value: "aeolian",
    label: { pt: "Eólico", en: "Aeolian", es: "Eólico", fr: "Éolien" },
    desc: { pt: "Formas criadas pelo transporte e deposição pelo vento: dunas, mantos de areia, depressões de deflação", en: "Forms created by wind transport and deposition: dunes, sand sheets, deflation depressions", es: "Formas creadas por el transporte y depósito eólico: dunas, mantos de arena, depresiones de deflación", fr: "Formes créées par le transport et le dépôt éoliens : dunes, nappes sableuses, dépressions de déflation" },
  },
  {
    value: "karst",
    label: { pt: "Cársico", en: "Karst", es: "Kárstico", fr: "Karstique" },
    desc: { pt: "Formas resultantes da dissolução de rochas solúveis (calcário, dolomito): dolinas, sumidouros, lapiezs", en: "Forms resulting from dissolution of soluble rocks (limestone, dolomite): sinkholes, swallow holes, karren", es: "Formas resultantes de la disolución de rocas solubles (caliza, dolomita): dolinas, sumideros, lapiaces", fr: "Formes résultant de la dissolution de roches solubles (calcaire, dolomie) : dolines, pertes, lapiés" },
  },
  {
    value: "estuarine",
    label: { pt: "Estuarino", en: "Estuarine", es: "Estuarino", fr: "Estuarien" },
    desc: { pt: "Zona de encontro entre rio e mar; influência de marés; depósitos mistos fluvio-marinhos", en: "Zone where river meets sea; tidal influence; mixed fluvial-marine deposits", es: "Zona de encuentro entre río y mar; influencia de mareas; depósitos mixtos fluvio-marinos", fr: "Zone de rencontre entre la rivière et la mer ; influence des marées ; dépôts mixtes fluvio-marins" },
  },
  {
    value: "beach",
    label: { pt: "Praial", en: "Beach", es: "Playero", fr: "Plage" },
    desc: { pt: "Faixa de areia ou sedimentos na margem de corpos d'água; submetida a dinâmica de ondas e marés", en: "Strip of sand or sediments at the margin of water bodies; subject to wave and tidal dynamics", es: "Franja de arena o sedimentos en el margen de cuerpos de agua; sujeta a dinámica de olas y mareas", fr: "Bande de sable ou de sédiments en bordure des plans d'eau ; soumise à la dynamique des vagues et des marées" },
  },
  {
    value: "deltaic",
    label: { pt: "Deltaico", en: "Deltaic", es: "Deltaico", fr: "Deltaïque" },
    desc: { pt: "Depósitos sedimentares na foz de rios; ambiente de transição entre sistema fluvial e marinho ou lacustre", en: "Sedimentary deposits at river mouths; transitional environment between fluvial and marine or lacustrine systems", es: "Depósitos sedimentarios en la desembocadura de ríos; ambiente de transición entre sistema fluvial y marino o lacustre", fr: "Dépôts sédimentaires à l'embouchure des rivières ; environnement de transition entre les systèmes fluvial et marin ou lacustre" },
  },
  {
    value: "erosive_coastal",
    label: { pt: "Costeiro Erosivo", en: "Erosive Coastal", es: "Costero Erosivo", fr: "Côtier Érosif" },
    desc: { pt: "Costa dominada por erosão de ondas sobre rochas ou sedimentos; falésias, plataformas de abrasão", en: "Coast dominated by wave erosion on rocks or sediments; sea cliffs, abrasion platforms", es: "Costa dominada por erosión de olas sobre rocas o sedimentos; acantilados, plataformas de abrasión", fr: "Côte dominée par l'érosion des vagues sur les roches ou les sédiments ; falaises marines, plates-formes d'abrasion" },
  },
];

const geomorphologyFields: FieldSchema[] = [
  {
    id: "exposure",
    label: { pt: "Exposição", en: "Exposure", es: "Exposición", fr: "Exposition" },
    type: "select",
    options: [
      {
        value: "windward",
        label: { pt: "Barlavento", en: "Windward", es: "Barlovento", fr: "Côté au vent" },
        desc: { pt: "Lado exposto ao vento; geralmente mais úmido e com vegetação mais densa", en: "Wind-exposed side; generally wetter with denser vegetation", es: "Lado expuesto al viento; generalmente más húmedo y con vegetación más densa", fr: "Côté exposé au vent ; généralement plus humide avec une végétation plus dense" },
      },
      {
        value: "leeward",
        label: { pt: "Sotavento", en: "Leeward", es: "Sotavento", fr: "Sous le vent" },
        desc: { pt: "Lado protegido do vento; geralmente mais seco e com vegetação mais rala", en: "Wind-sheltered side; generally drier with sparser vegetation", es: "Lado protegido del viento; generalmente más seco y con vegetación más rala", fr: "Côté abrité du vent ; généralement plus sec avec une végétation plus clairsemée" },
      },
      {
        value: "not_applicable",
        label: { pt: "Não se Aplica", en: "Not Applicable", es: "No Aplica", fr: "Sans objet" },
        desc: { pt: "Para terrenos planos ou onde a exposição ao vento não é fator relevante na diferenciação ambiental", en: "For flat terrain or where wind exposure is not a relevant factor in environmental differentiation", es: "Para terrenos planos o donde la exposición al viento no es un factor relevante en la diferenciación ambiental", fr: "Pour les terrains plats ou lorsque l'exposition au vent n'est pas un facteur pertinent de différenciation environnementale" },
      },
    ],
  },
  {
    id: "slope",
    label: { pt: "Declive", en: "Slope", es: "Pendiente", fr: "Pente" },
    type: "select",
    options: [
      {
        value: "flat",
        label: { pt: "Plano (<1°)", en: "Flat (<1°)", es: "Plano (<1°)", fr: "Plat (<1°)" },
        desc: { pt: "Terreno sem inclinação perceptível; favorece acúmulo de água e solos profundos", en: "Terrain without perceptible inclination; favors water accumulation and deep soils", es: "Terreno sin inclinación perceptible; favorece la acumulación de agua y suelos profundos", fr: "Terrain sans inclinaison perceptible ; favorise l'accumulation d'eau et les sols profonds" },
      },
      {
        value: "very_gentle",
        label: { pt: "Muito suave (1-5°)", en: "Very gentle (1-5°)", es: "Muy suave (1-5°)", fr: "Très doux (1-5°)" },
        desc: { pt: "Inclinação leve; escoamento superficial lento; baixo risco erosivo", en: "Slight inclination; slow surface runoff; low erosion risk", es: "Inclinación leve; escorrentía superficial lenta; bajo riesgo erosivo", fr: "Légère inclinaison ; ruissellement de surface lent ; faible risque d'érosion" },
      },
      {
        value: "gentle",
        label: { pt: "Suave (5-10°)", en: "Gentle (5-10°)", es: "Suave (5-10°)", fr: "Doux (5-10°)" },
        desc: { pt: "Inclinação moderada; escoamento superficial moderado; risco erosivo médio em solos expostos", en: "Moderate inclination; moderate surface runoff; medium erosion risk on exposed soils", es: "Inclinación moderada; escorrentía superficial moderada; riesgo erosivo medio en suelos expuestos", fr: "Inclinaison modérée ; ruissellement de surface modéré ; risque d'érosion moyen sur les sols exposés" },
      },
      {
        value: "moderate",
        label: { pt: "Moderado (10-30°)", en: "Moderate (10-30°)", es: "Moderado (10-30°)", fr: "Modéré (10-30°)" },
        desc: { pt: "Encosta com inclinação pronunciada; solos rasos; alta suscetibilidade à erosão laminar e em sulcos", en: "Slope with pronounced inclination; shallow soils; high susceptibility to sheet and rill erosion", es: "Ladera con inclinación pronunciada; suelos poco profundos; alta susceptibilidad a la erosión laminar y en surcos", fr: "Versant à inclinaison prononcée ; sols peu profonds ; forte susceptibilité à l'érosion en nappe et en rigoles" },
      },
      {
        value: "steep",
        label: { pt: "Íngreme (>30°)", en: "Steep (>30°)", es: "Empinado (>30°)", fr: "Raide (>30°)" },
        desc: { pt: "Encosta muito inclinada ou escarpa; solos muito rasos ou ausentes; dominância de processos gravitacionais", en: "Very steep slope or escarpment; very shallow or absent soils; dominance of gravitational processes", es: "Ladera muy inclinada o escarpa; suelos muy poco profundos o ausentes; predominio de procesos gravitacionales", fr: "Versant très incliné ou escarpement ; sols très peu profonds ou absents ; dominance des processus gravitaires" },
      },
    ],
  },
  {
    id: "topographic_position",
    label: { pt: "Posição Topográfica", en: "Topographic Position", es: "Posición Topográfica", fr: "Position Topographique" },
    type: "select",
    options: [
      {
        value: "top",
        label: { pt: "Topo", en: "Top", es: "Cima", fr: "Sommet" },
        desc: { pt: "Parte mais elevada da vertente; solos rasos; maior exposição ao vento e à insolação", en: "Highest part of the hillslope; shallow soils; greater exposure to wind and solar radiation", es: "Parte más elevada de la vertiente; suelos poco profundos; mayor exposición al viento y la insolación", fr: "Partie la plus élevée du versant ; sols peu profonds ; plus grande exposition au vent et au rayonnement solaire" },
      },
      {
        value: "mid_slope",
        label: { pt: "Intermediária", en: "Mid-slope", es: "Intermedia", fr: "Mi-versant" },
        desc: { pt: "Porção mediana da encosta; transição entre processos de topo e de base; solos moderados", en: "Middle portion of the slope; transition between hilltop and footslope processes; moderate soils", es: "Porción media de la ladera; transición entre procesos de cima y de base; suelos moderados", fr: "Partie médiane du versant ; transition entre processus de sommet et de bas de versant ; sols modérés" },
      },
      {
        value: "lower",
        label: { pt: "Inferior", en: "Lower", es: "Inferior", fr: "Bas de versant" },
        desc: { pt: "Base da encosta ou planície; concentração de sedimentos e umidade; solos profundos e úmidos", en: "Slope base or plain; concentration of sediments and moisture; deep and wet soils", es: "Base de la ladera o planicie; concentración de sedimentos y humedad; suelos profundos y húmedos", fr: "Base du versant ou plaine ; concentration de sédiments et d'humidité ; sols profonds et humides" },
      },
    ],
  },
  {
    id: "slope_shape",
    label: { pt: "Forma do Relevo", en: "Landform", es: "Forma del Relieve", fr: "Forme du Relief" },
    type: "select",
    options: [
      {
        value: "concave",
        label: { pt: "Côncava", en: "Concave", es: "Cóncava", fr: "Concave" },
        desc: { pt: "Perfil em forma de concha; desacelera o fluxo de água; acumula sedimentos e umidade; favorece solos mais profundos", en: "Shell-shaped profile; slows water flow; accumulates sediments and moisture; favors deeper soils", es: "Perfil en forma de cuenco; desacelera el flujo de agua; acumula sedimentos y humedad; favorece suelos más profundos", fr: "Profil en forme de cuvette ; ralentit le flux d'eau ; accumule sédiments et humidité ; favorise les sols plus profonds" },
      },
      {
        value: "rectilinear",
        label: { pt: "Retilínea", en: "Rectilinear", es: "Rectilínea", fr: "Rectiligne" },
        desc: { pt: "Perfil reto; fluxo uniforme de água e sedimentos ao longo da encosta", en: "Straight profile; uniform flow of water and sediments along the slope", es: "Perfil recto; flujo uniforme de agua y sedimentos a lo largo de la ladera", fr: "Profil rectiligne ; flux uniforme d'eau et de sédiments le long du versant" },
      },
      {
        value: "convex",
        label: { pt: "Convexa", en: "Convex", es: "Convexa", fr: "Convexe" },
        desc: { pt: "Perfil em forma de cúpula; acelera o fluxo de água; favorece erosão e solos rasos", en: "Dome-shaped profile; accelerates water flow; favors erosion and shallow soils", es: "Perfil en forma de domo; acelera el flujo de agua; favorece la erosión y los suelos poco profundos", fr: "Profil en dôme ; accélère le flux d'eau ; favorise l'érosion et les sols peu profonds" },
      },
    ],
  },
  {
    id: "geomorphology_type",
    label: { pt: "Ambiente Geomorfológico", en: "Geomorphological Environment", es: "Ambiente Geomorfológico", fr: "Environnement Géomorphologique" },
    type: "multiselect",
    // FieldRenderer dispatches on renderAs ?? type, and only knows how to draw
    // a multi-select as "checkbox" (a list of Checkboxes) - "multiselect" is
    // just the kernel's semantic type, not a UI widget name on its own.
    renderAs: "checkbox",
    options: geomorphologyTypeOptions,
  },
];

// --- Cover, Surface and Soil ---

export const colorPatternOptions: SelectOption[] = [
  { value: "homogeneous", label: { pt: "Homogêneo", en: "Homogeneous", es: "Homogéneo", fr: "Homogène" }, desc: { pt: "Toda a camada apresenta uma única cor uniforme, sem manchas, listras ou variações cromáticas discerníveis. Indica condições estáveis de drenagem e pedogênese homogênea ao longo da camada.", en: "The entire layer presents a single uniform color, without spots, streaks, or discernible chromatic variations. Indicates stable drainage conditions and homogeneous pedogenesis throughout the layer.", es: "Toda la capa presenta un único color uniforme, sin manchas, rayas ni variaciones cromáticas discernibles. Indica condiciones estables de drenaje y pedogénesis homogénea a lo largo de la capa.", fr: "Toute la couche présente une seule couleur uniforme, sans taches, raies ou variations chromatiques discernables. Indique des conditions de drainage stables et une pédogenèse homogène dans toute la couche." } },
  { value: "variegated", label: { pt: "Variegado", en: "Variegated", es: "Variegado", fr: "Bigarré" }, desc: { pt: "A camada apresenta duas ou mais cores visíveis, ou manchas de cor diferente sobre uma cor de fundo dominante. Indica alternância de processos de oxidação (manchas avermelhadas) e redução (manchas acinzentadas), associada a flutuações do lençol freático. Registrar a cor dominante e a cor secundária.", en: "The layer presents two or more visible colors, or spots of a different color on a dominant background. Indicates alternating oxidation (reddish spots) and reduction (grayish spots) processes, associated with water table fluctuations. Record both the dominant and secondary colors.", es: "La capa presenta dos o más colores visibles, o manchas de color diferente sobre un color de fondo dominante. Indica alternancia de procesos de oxidación (manchas rojizas) y reducción (manchas grisáceas), asociada a fluctuaciones del nivel freático. Registrar el color dominante y el secundario.", fr: "La couche présente deux couleurs ou plus visibles, ou des taches de couleur différente sur une couleur de fond dominante. Indique une alternance de processus d'oxydation (taches rougeâtres) et de réduction (taches grisâtres), associée à des fluctuations de la nappe. Enregistrer les couleurs dominante et secondaire." } },
];

export const colorTermOptions: SelectOption[] = [
  { value: "red",             label: { pt: "Vermelho",           en: "Red",            es: "Rojo",           fr: "Rouge" }, desc: { pt: "Coloração vermelha intensa, típica de solos com alto teor de hematita (Fe₂O₃). Indica intemperismo avançado e drenagem livre e prolongada. Frequente em Latossolos Vermelhos e Nitossolos Vermelhos de regiões tropicais úmidas.", en: "Intense red color, typical of soils with high hematite content (Fe₂O₃). Indicates advanced weathering and prolonged free drainage. Frequent in Red Latosols and Red Nitosols of humid tropical regions.", es: "Coloración roja intensa, típica de suelos con alto contenido de hematita (Fe₂O₃). Indica meteorización avanzada y drenaje libre y prolongado. Frecuente en Latosoles Rojos y Nitosoles Rojos de regiones tropicales húmedas.", fr: "Couleur rouge intense, typique des sols à haute teneur en hématite (Fe₂O₃). Indique une altération avancée et un drainage libre et prolongé. Fréquent dans les Latosols Rouges et Nitosols Rouges des régions tropicales humides." } },
  { value: "reddish_brown",   label: { pt: "Bruno-avermelhado",  en: "Reddish brown",  es: "Pardo-rojizo",   fr: "Brun-rougeâtre" }, desc: { pt: "Coloração pardo-avermelhada, com teor moderado de óxidos de ferro. Indica intemperismo intermediário. Frequente em Argissolos Vermelho-Amarelos e em horizontes B de Cambissolos.", en: "Reddish brown color with moderate iron oxide content. Indicates intermediate weathering. Frequent in Red-Yellow Argisols and in B horizons of Cambisols.", es: "Coloración pardo-rojiza, con contenido moderado de óxidos de hierro. Indica meteorización intermedia. Frecuente en Argisoles Rojo-Amarillos y en horizontes B de Cambisoles.", fr: "Couleur brun rougeâtre, avec une teneur modérée en oxydes de fer. Indique une altération intermédiaire. Fréquent dans les Argisols Rouge-Jaune et dans les horizons B des Cambisols." } },
  { value: "yellowish_red",   label: { pt: "Vermelho-amarelado", en: "Yellowish red",  es: "Rojo-amarillento", fr: "Rouge jaunâtre" }, desc: { pt: "Coloração vermelho-amarelada, resultante da coexistência de hematita e goethita. Típica de solos bem drenados em regiões úmidas. Frequente em Latossolos e Argissolos Vermelho-Amarelos.", en: "Yellowish red color resulting from the coexistence of hematite and goethite. Typical of well-drained soils in humid regions. Frequent in Latosols and Red-Yellow Argisols.", es: "Coloración rojo-amarillenta, resultado de la coexistencia de hematita y goethita. Típica de suelos bien drenados en regiones húmedas. Frecuente en Latosoles y Argisoles Rojo-Amarillos.", fr: "Couleur rouge jaunâtre résultant de la coexistence d'hématite et de goéthite. Typique des sols bien drainés dans les régions humides. Fréquent dans les Latosols et Argisols Rouge-Jaune." } },
  { value: "strong_brown",    label: { pt: "Bruno-forte",        en: "Strong brown",   es: "Pardo fuerte",   fr: "Brun fort" }, desc: { pt: "Coloração parda intensa, com goethita como óxido de ferro dominante. Indica boa drenagem. Frequente nos horizontes B de Argissolos e Cambissolos de regiões com estação seca moderada.", en: "Intense brown color with goethite as the dominant iron oxide. Indicates good drainage. Frequent in B horizons of Argisols and Cambisols in regions with moderate dry seasons.", es: "Coloración parda intensa, con goethita como óxido de hierro dominante. Indica buen drenaje. Frecuente en los horizontes B de Argisoles y Cambisoles de regiones con estación seca moderada.", fr: "Couleur brune intense avec la goéthite comme oxyde de fer dominant. Indique un bon drainage. Fréquent dans les horizons B des Argisols et Cambisols des régions à saison sèche modérée." } },
  { value: "yellowish_brown", label: { pt: "Bruno-amarelado",    en: "Yellowish brown", es: "Pardo-amarillento", fr: "Brun jaunâtre" }, desc: { pt: "Coloração pardo-amarelada, com goethita dominante e intemperismo moderado. Frequente no topo de perfis lateríticos e em horizontes de transição. Comum em Argissolos e Cambissolos de regiões tropicais com drenagem moderada.", en: "Yellowish brown color with dominant goethite and moderate weathering. Frequent at the top of lateritic profiles and in transitional horizons. Common in Argisols and Cambisols of tropical regions with moderate drainage.", es: "Coloración pardo-amarillenta, con goethita dominante y meteorización moderada. Frecuente en la parte superior de perfiles lateríticos y en horizontes de transición. Común en Argisoles y Cambisoles de regiones tropicales con drenaje moderado.", fr: "Couleur brun jaunâtre avec goéthite dominante et altération modérée. Fréquent au sommet des profils latéritiques et dans les horizons de transition. Commun dans les Argisols et Cambisols des régions tropicales à drainage modéré." } },
  { value: "brownish_yellow", label: { pt: "Amarelo-brunado",    en: "Brownish yellow", es: "Amarillo-parduzco", fr: "Jaune brunâtre" }, desc: { pt: "Coloração amarelo-acastanhada, associada a solos muito intemperizados com baixa concentração de óxidos de ferro. Diagnóstica de Latossolos Amarelos. Indica alto grau de lixiviação de bases e cátions.", en: "Brownish yellow color associated with highly weathered soils with low iron oxide concentration. Diagnostic of Yellow Latosols. Indicates a high degree of leaching of bases and cations.", es: "Coloración amarillo-parduzca, asociada a suelos muy meteorizados con baja concentración de óxidos de hierro. Diagnóstica de Latosoles Amarillos. Indica alto grado de lixiviación de bases y cationes.", fr: "Couleur jaune brunâtre associée aux sols très altérés avec une faible concentration en oxydes de fer. Diagnostique des Latosols Jaunes. Indique un fort degré de lessivage des bases et des cations." } },
  { value: "yellow",          label: { pt: "Amarelo",            en: "Yellow",         es: "Amarillo",       fr: "Jaune" }, desc: { pt: "Coloração amarela, resultante de lixiviação extrema e mínima concentração de óxidos de ferro. Indica alta saturação por Al³⁺ e baixa fertilidade natural. Diagnóstica de Latossolos Amarelos em estágio avançado de intemperismo, comum na Amazônia e no litoral nordestino.", en: "Yellow color resulting from extreme leaching and minimal iron oxide concentration. Indicates high Al³⁺ saturation and low natural fertility. Diagnostic of Yellow Latosols in advanced weathering stage, common in the Amazon and northeastern Brazilian coast.", es: "Coloración amarilla, resultado de lixiviación extrema y mínima concentración de óxidos de hierro. Indica alta saturación por Al³⁺ y baja fertilidad natural. Diagnóstica de Latosoles Amarillos en estado avanzado de meteorización, común en la Amazonía y el litoral nororiental.", fr: "Couleur jaune résultant d'un lessivage extrême et d'une concentration minimale en oxydes de fer. Indique une haute saturation en Al³⁺ et une faible fertilité naturelle. Diagnostique des Latosols Jaunes à stade d'altération avancé, commun en Amazonie et sur le littoral nord-est brésilien." } },
  { value: "brown",           label: { pt: "Bruno",              en: "Brown",          es: "Pardo",          fr: "Brun" }, desc: { pt: "Coloração parda neutra, com teor moderado de matéria orgânica e intemperismo intermediário. Comum em horizontes A e B de Cambissolos, Argissolos e Neossolos. Não indica hidromorfismo nem acúmulo expressivo de óxidos de ferro.", en: "Neutral brown color with moderate organic matter content and intermediate weathering. Common in A and B horizons of Cambisols, Argisols, and Neosols. Does not indicate hydromorphism or significant iron oxide accumulation.", es: "Coloración parda neutra, con contenido moderado de materia orgánica y meteorización intermedia. Común en horizontes A y B de Cambisoles, Argisoles y Neosoles. No indica hidromorfismo ni acumulación significativa de óxidos de hierro.", fr: "Couleur brune neutre avec une teneur modérée en matière organique et une altération intermédiaire. Commun dans les horizons A et B des Cambisols, Argisols et Néosols. N'indique pas d'hydromorphie ni d'accumulation significative d'oxydes de fer." } },
  { value: "dark_brown",      label: { pt: "Bruno-escuro",       en: "Dark brown",     es: "Pardo oscuro",   fr: "Brun foncé" }, desc: { pt: "Coloração parda escura, resultante de teor elevado de matéria orgânica. Típica de horizontes A moderados, proeminentes ou húmicos. A cor escura indica boa atividade biológica e acúmulo de húmus.", en: "Dark brown color resulting from high organic matter content. Typical of moderate, prominent, or humic A horizons. The dark color indicates good biological activity and humus accumulation.", es: "Coloración parda oscura, resultado de alto contenido de materia orgánica. Típica de horizontes A moderados, prominentes o húmicos. El color oscuro indica buena actividad biológica y acumulación de humus.", fr: "Couleur brun foncé résultant d'une haute teneur en matière organique. Typique des horizons A modérés, proéminents ou humiques. La couleur sombre indique une bonne activité biologique et une accumulation d'humus." } },
  { value: "grayish_brown",   label: { pt: "Bruno-acinzentado",  en: "Grayish brown",  es: "Pardo-grisáceo", fr: "Brun grisâtre" }, desc: { pt: "Coloração pardo-acinzentada, indicando gleização incipiente ou alternância de condições de drenagem. A redução do croma em relação ao bruno indica início de processos redutores na camada, associados a saturação hídrica periódica.", en: "Grayish brown color indicating incipient gleization or alternating drainage conditions. The reduction in chroma relative to brown indicates the beginning of reducing processes in the layer, associated with periodic waterlogging.", es: "Coloración pardo-grisácea, que indica gleización incipiente o alternancia de condiciones de drenaje. La reducción del croma respecto al pardo indica inicio de procesos reductores en la capa, asociados a saturación hídrica periódica.", fr: "Couleur brun grisâtre indiquant une gléisation incipiente ou une alternance de conditions de drainage. La réduction du chroma par rapport au brun indique le début de processus réducteurs dans la couche, associés à une saturation hydrique périodique." } },
  { value: "gray",            label: { pt: "Cinzento",           en: "Gray",           es: "Gris",           fr: "Gris" }, desc: { pt: "Coloração cinzenta com baixo croma, indicando horizonte gleizado em condição anaeróbia por saturação hídrica. O ferro foi reduzido a Fe²⁺ e parcialmente removido, resultando na cor característica. Diagnóstica de Gleissolos e horizontes glei em outros solos.", en: "Gray color with low chroma, indicating a gleyed horizon under anaerobic conditions from waterlogging. Iron was reduced to Fe²⁺ and partially removed, resulting in the characteristic color. Diagnostic of Gleysols and gley horizons in other soils.", es: "Coloración gris con bajo croma, que indica horizonte gleizado en condición anaeróbica por saturación hídrica. El hierro fue reducido a Fe²⁺ y parcialmente removido, resultando en el color característico. Diagnóstica de Gleisoles y horizontes glei en otros suelos.", fr: "Couleur grise à faible chroma, indiquant un horizon engorgé en condition anaérobie par saturation hydrique. Le fer a été réduit en Fe²⁺ et partiellement éliminé. Diagnostique des Gleysols et des horizons gley dans d'autres sols." } },
  { value: "dark_gray",       label: { pt: "Cinzento-escuro",    en: "Dark gray",      es: "Gris oscuro",    fr: "Gris foncé" }, desc: { pt: "Coloração cinzenta escura, combinando gleização com acúmulo de matéria orgânica. Indica horizonte gleico com atividade biológica preservada em condições anaeróbias, ou horizonte A de áreas permanentemente alagadas.", en: "Dark gray color combining gleization with organic matter accumulation. Indicates a gley horizon with biological activity preserved under anaerobic conditions, or an A horizon in permanently flooded areas.", es: "Coloración gris oscura, que combina gleización con acumulación de materia orgánica. Indica horizonte gleico con actividad biológica preservada en condiciones anaeróbicas, o horizonte A de áreas permanentemente inundadas.", fr: "Couleur gris foncé combinant gléisation et accumulation de matière organique. Indique un horizon gley avec activité biologique préservée en conditions anaérobies, ou un horizon A de zones en permanence inondées." } },
  { value: "black",           label: { pt: "Preto",              en: "Black",          es: "Negro",          fr: "Noir" }, desc: { pt: "Coloração preta, resultante de acúmulo muito elevado de matéria orgânica (horizontes A chernozêmico ou húmico) ou de gleização intensa. Indica alta fertilidade natural quando associado à matéria orgânica, ou hidromorfismo permanente quando associado à gleização.", en: "Black color resulting from very high organic matter accumulation (chernozemic or humic A horizons) or intense gleization. Indicates high natural fertility when associated with organic matter, or permanent hydromorphism when associated with gleization.", es: "Coloración negra, resultado de acumulación muy elevada de materia orgánica (horizontes A chernozémico o húmico) o de gleización intensa. Indica alta fertilidad natural cuando asociada a materia orgánica, o hidromorfismo permanente cuando asociada a gleización.", fr: "Couleur noire résultant d'une accumulation très élevée de matière organique (horizons A chernozémique ou humique) ou d'une gléisation intense. Indique une haute fertilité naturelle quand associée à la matière organique, ou un hydromorphisme permanent quand associée à la gléisation." } },
];

export const textureOptions: SelectOption[] = [
  { value: "sand",               label: { pt: "Areia",                   en: "Sand",           es: "Arena",             fr: "Sable" }, desc: { pt: "Solo arenoso puro. Partículas de areia visíveis a olho nu. Ao umedecer e amassar, não forma fita nem bola coesa; esfacela facilmente. Sem plasticidade e sem pegajosidade.", en: "Pure sandy soil. Sand particles visible to the naked eye. When wet and kneaded, does not form a ribbon or cohesive ball; crumbles easily. No plasticity or stickiness.", es: "Suelo arenoso puro. Partículas de arena visibles a simple vista. Al humedecer y amasar, no forma cinta ni bola cohesiva; se desmorona fácilmente. Sin plasticidad ni pegajosidad.", fr: "Sol sableux pur. Particules de sable visibles à l'œil nu. Humidifié et pétri, ne forme pas de ruban ni de boule cohésive ; s'émiette facilement. Sans plasticité ni adhérence." } },
  { value: "loamy_sand",         label: { pt: "Areia franca",            en: "Loamy sand",     es: "Arena franca",      fr: "Sable limoneux" }, desc: { pt: "Predominantemente arenoso, com pequena fração de argila. Forma uma bola frágil ao ser pressionado úmido, mas não forma fita. Sem pegajosidade perceptível.", en: "Predominantly sandy with a small clay fraction. Forms a fragile ball when pressed moist but does not form a ribbon. No noticeable stickiness.", es: "Predominantemente arenoso con pequeña fracción de arcilla. Forma una bola frágil al presionar húmedo, pero no forma cinta. Sin pegajosidad perceptible.", fr: "Principalement sableux avec une petite fraction d'argile. Forme une boule fragile quand pressé humide, mais ne forme pas de ruban. Pas d'adhérence perceptible." } },
  { value: "sandy_loam",         label: { pt: "Franco-arenoso",          en: "Sandy loam",     es: "Franco arenoso",    fr: "Limon sableux" }, desc: { pt: "Textura mista com predominância de areia. Forma fita curta e friável ao ser amassado úmido. Levemente plástico e levemente pegajoso. A sensação granulosa da areia é facilmente perceptível.", en: "Mixed texture with predominance of sand. Forms a short, friable ribbon when kneaded moist. Slightly plastic and slightly sticky. The grainy feel of sand is easily noticeable.", es: "Textura mixta con predominio de arena. Forma cinta corta y friable al amasarse húmedo. Levemente plástico y levemente pegajoso. La sensación granulosa de la arena es fácilmente perceptible.", fr: "Texture mixte à dominance sableuse. Forme un ruban court et friable pétri humide. Légèrement plastique et légèrement adhérent. La sensation granuleuse du sable est facilement perceptible." } },
  { value: "loam",               label: { pt: "Franco",                  en: "Loam",           es: "Franco",            fr: "Limon" }, desc: { pt: "Textura equilibrada entre areia, silte e argila. Forma fita de comprimento médio ao ser amassado úmido. Moderadamente plástico e moderadamente pegajoso. Sem dominância tátil de nenhum componente.", en: "Balanced texture among sand, silt, and clay. Forms a medium-length ribbon when kneaded moist. Moderately plastic and moderately sticky. No tactile dominance of any single component.", es: "Textura equilibrada entre arena, limo y arcilla. Forma cinta de longitud media al amasarse húmedo. Moderadamente plástico y moderadamente pegajoso. Sin dominancia táctil de ningún componente.", fr: "Texture équilibrée entre sable, limon et argile. Forme un ruban de longueur moyenne pétri humide. Modérément plastique et modérément adhérent. Pas de dominance tactile d'un seul composant." } },
  { value: "silt_loam",          label: { pt: "Franco-siltoso",          en: "Silt loam",      es: "Franco limoso",     fr: "Limon argileux" }, desc: { pt: "Sensação sedosa e suave dominante ao tato. Moderadamente plástico e moderadamente pegajoso. Forma fita de comprimento médio. O silte confere uma maciez característica que diferencia esta classe das texturais argilosas.", en: "Dominant silky and smooth feel to the touch. Moderately plastic and moderately sticky. Forms a medium-length ribbon. The silt gives a characteristic softness that distinguishes this class from clayey textures.", es: "Sensación sedosa y suave dominante al tacto. Moderadamente plástico y moderadamente pegajoso. Forma cinta de longitud media. El limo confiere una suavidad característica que diferencia esta clase de las texturas arcillosas.", fr: "Sensation soyeuse et douce dominante au toucher. Modérément plastique et modérément adhérent. Forme un ruban de longueur moyenne. Le limon confère une douceur caractéristique qui distingue cette classe des textures argileuses." } },
  { value: "silt",               label: { pt: "Silte",                   en: "Silt",           es: "Limo",              fr: "Limon fin" }, desc: { pt: "Quase exclusivamente silte. Extremamente sedoso ao tato, como farinha fina. Muito pouco plástico, sem pegajosidade expressiva. Raro em solos tropicais brasileiros; mais frequente em depósitos aluviais recentes.", en: "Almost exclusively silt. Extremely silky to the touch, like fine flour. Very slightly plastic, with no significant stickiness. Rare in Brazilian tropical soils; more common in recent alluvial deposits.", es: "Casi exclusivamente limo. Extremadamente sedoso al tacto, como harina fina. Muy poco plástico, sin pegajosidad significativa. Raro en suelos tropicales brasileños; más frecuente en depósitos aluviales recientes.", fr: "Presque exclusivement du limon. Extrêmement soyeux au toucher, comme de la farine fine. Très légèrement plastique, sans adhérence significative. Rare dans les sols tropicaux brésiliens ; plus fréquent dans les dépôts alluviaux récents." } },
  { value: "clay_loam",          label: { pt: "Franco-argiloso",         en: "Clay loam",      es: "Franco arcilloso",  fr: "Argile limoneuse" }, desc: { pt: "Claramente plástico e pegajoso ao tato. Forma fita longa e contínua ao ser amassado úmido. Sem dominância de areia ou silte. Ao secar, forma torrões de média dureza.", en: "Clearly plastic and sticky to the touch. Forms a long, continuous ribbon when kneaded moist. No dominance of sand or silt. When dry, forms medium-hard clods.", es: "Claramente plástico y pegajoso al tacto. Forma cinta larga y continua al amasarse húmedo. Sin predominio de arena ni limo. Al secarse, forma terrones de dureza media.", fr: "Clairement plastique et adhérent au toucher. Forme un ruban long et continu pétri humide. Pas de dominance de sable ou de limon. En séchant, forme des mottes de dureté moyenne." } },
  { value: "sandy_clay_loam",    label: { pt: "Franco-argilo-arenoso",   en: "Sandy clay loam", es: "Franco arcillo-arenoso", fr: "Argile sableuse limoneuse" }, desc: { pt: "Plástico e pegajoso com presença de areia claramente perceptível. Forma fita longa, mas com superfície áspera pela areia. A combinação de pegajosidade e granulosidade é característica desta classe.", en: "Plastic and sticky with clearly perceptible presence of sand. Forms a long ribbon but with a rough surface due to sand. The combination of stickiness and graininess is characteristic of this class.", es: "Plástico y pegajoso con presencia de arena claramente perceptible. Forma cinta larga, pero con superficie rugosa por la arena. La combinación de pegajosidad y granulometría es característica de esta clase.", fr: "Plastique et adhérent avec présence de sable clairement perceptible. Forme un ruban long mais avec une surface rugueuse due au sable. La combinaison d'adhérence et de granulométrie est caractéristique de cette classe." } },
  { value: "silty_clay_loam",    label: { pt: "Franco-argilo-siltoso",   en: "Silty clay loam", es: "Franco arcillo-limoso",  fr: "Argile limono-silteuse" }, desc: { pt: "Muito plástico e muito pegajoso com sensação sedosa intensa. Forma fita longa e brilhosa. A plasticidade é alta, mas a superfície da fita é mais lisa que nas classes argilosas puras, pela presença do silte.", en: "Very plastic and very sticky with intense silky feel. Forms a long and shiny ribbon. Plasticity is high, but the ribbon surface is smoother than in pure clayey classes due to the presence of silt.", es: "Muy plástico y muy pegajoso con intensa sensación sedosa. Forma cinta larga y brillante. La plasticidad es alta, pero la superficie de la cinta es más lisa que en las clases arcillosas puras, por la presencia del limo.", fr: "Très plastique et très adhérent avec une sensation soyeuse intense. Forme un ruban long et brillant. La plasticité est élevée, mais la surface du ruban est plus lisse que dans les classes argileuses pures, en raison de la présence du limon." } },
  { value: "sandy_clay",         label: { pt: "Argilo-arenoso",          en: "Sandy clay",     es: "Arcillo arenoso",   fr: "Argile sableuse" }, desc: { pt: "Muito plástico e muito pegajoso, com areia visivelmente incorporada à massa. A areia não reduz a plasticidade de forma significativa. Ao secar, forma torrões duros e angulosos com partículas de areia visíveis.", en: "Very plastic and very sticky, with sand visibly incorporated into the mass. The sand does not significantly reduce plasticity. When dry, forms hard angular clods with visible sand particles.", es: "Muy plástico y muy pegajoso, con arena visiblemente incorporada a la masa. La arena no reduce significativamente la plasticidad. Al secarse, forma terrones duros y angulosos con partículas de arena visibles.", fr: "Très plastique et très adhérent, avec du sable visiblement incorporé dans la masse. Le sable ne réduit pas significativement la plasticité. En séchant, forme des mottes dures et anguleuses avec des particules de sable visibles." } },
  { value: "silty_clay",         label: { pt: "Argilo-siltoso",          en: "Silty clay",     es: "Arcillo limoso",    fr: "Argile silteuse" }, desc: { pt: "Muito plástico, muito pegajoso e muito sedoso simultaneamente. Forma fita muito longa e brilhosa. A sensação de seda e de cola ao mesmo tempo é característica desta classe. Ao secar, torna-se muito duro.", en: "Very plastic, very sticky, and very silky simultaneously. Forms a very long and shiny ribbon. The simultaneous feeling of silk and glue is characteristic of this class. When dry, becomes very hard.", es: "Muy plástico, muy pegajoso y muy sedoso simultáneamente. Forma cinta muy larga y brillante. La sensación simultánea de seda y pegamento es característica de esta clase. Al secarse, se vuelve muy duro.", fr: "Très plastique, très adhérent et très soyeux simultanément. Forme un ruban très long et brillant. La sensation simultanée de soie et de colle est caractéristique de cette classe. En séchant, devient très dur." } },
  { value: "clay",               label: { pt: "Argila",                  en: "Clay",           es: "Arcilla",           fr: "Argile" }, desc: { pt: "Extremamente plástico e pegajoso. Forma fita muito longa, brilhosa e resistente à ruptura. Ao umedecer, absorve água lentamente e incha. Ao secar, contrai fortemente, formando fissuras e torrões extremamente duros. Teor de argila superior a 40%, podendo ultrapassar 60%.", en: "Extremely plastic and sticky. Forms a very long, shiny ribbon that resists breaking. When wetted, absorbs water slowly and swells. When dry, contracts strongly, forming cracks and extremely hard clods. Clay content above 40%, potentially exceeding 60%.", es: "Extremadamente plástico y pegajoso. Forma cinta muy larga, brillante y resistente a la ruptura. Al humedecerse, absorbe agua lentamente e hincha. Al secarse, se contrae fuertemente, formando grietas y terrones extremadamente duros. Contenido de arcilla superior al 40%, pudiendo superar el 60%.", fr: "Extrêmement plastique et adhérent. Forme un ruban très long, brillant et résistant à la rupture. Humidifié, absorbe l'eau lentement et gonfle. Séché, se contracte fortement, formant des fissures et des mottes extrêmement dures. Teneur en argile supérieure à 40 %, pouvant dépasser 60 %." } },
];

export const structureOptions: SelectOption[] = [
  { value: "single_grain",       label: { pt: "Grãos simples",      en: "Single grain",       es: "Grano suelto",        fr: "Grain simple" }, desc: { pt: "Cada partícula comporta-se de forma independente, sem ligação com as demais. Estrutura típica de solos arenosos ou de horizontes muito lixiviados. Ao tentar formar um torrão, o material se esfacela imediatamente.", en: "Each particle behaves independently, with no bonding to others. Typical structure of sandy soils or highly leached horizons. When attempting to form a clod, the material crumbles immediately.", es: "Cada partícula se comporta de forma independiente, sin ligación con las demás. Estructura típica de suelos arenosos o de horizontes muy lixiviados. Al intentar formar un terrón, el material se deshace inmediatamente.", fr: "Chaque particule se comporte de façon indépendante, sans liaison avec les autres. Structure typique des sols sableux ou des horizons très lessivés. En tentant de former une motte, le matériau s'émiette immédiatement." } },
  { value: "massive",            label: { pt: "Maciça",             en: "Massive",            es: "Masiva",              fr: "Massive" }, desc: { pt: "Massa coesa sem agregados visíveis. O material não apresenta planos de fratura preferenciais; ao ser rompido, gera fragmentos de formato irregular. Pode indicar compactação, horizonte coeso, plíntico ou material de origem com cimentação.", en: "Coherent mass without visible aggregates. The material shows no preferential fracture planes; when broken, generates irregularly shaped fragments. May indicate compaction, cemented, plinthic, or cohesive horizon.", es: "Masa cohesiva sin agregados visibles. El material no presenta planos de fractura preferenciales; al romperse, genera fragmentos de formato irregular. Puede indicar compactación, horizonte cohesivo, plíntico o material de origen con cementación.", fr: "Masse cohésive sans agrégats visibles. Le matériau ne présente pas de plans de fracture préférentiels ; en se cassant, génère des fragments de forme irrégulière. Peut indiquer une compaction, un horizon cohésif, plinthique ou un matériau d'origine cimenté." } },
  { value: "granular",           label: { pt: "Granular",           en: "Granular",           es: "Granular",            fr: "Granulaire" }, desc: { pt: "Agregados pequenos, esféricos ou subesféricos, soltos entre si como grânulos de terra. Indica alta atividade biológica e boa incorporação de matéria orgânica. Comum em horizontes A bem desenvolvidos. Favorece alta porosidade e boa drenagem.", en: "Small, spherical or subspherical aggregates, loosely arranged like soil granules. Indicates high biological activity and good organic matter incorporation. Common in well-developed A horizons. Favors high porosity and good drainage.", es: "Agregados pequeños, esféricos o subesféricos, sueltos entre sí como gránulos de tierra. Indica alta actividad biológica e buena incorporación de materia orgánica. Común en horizontes A bien desarrollados. Favorece alta porosidad y buen drenaje.", fr: "Agrégats petits, sphériques ou subsphériques, lâchement arrangés comme des granules de terre. Indique une haute activité biologique et une bonne incorporation de matière organique. Commun dans les horizons A bien développés. Favorise une haute porosité et un bon drainage." } },
  { value: "angular_blocky",     label: { pt: "Blocos angulares",   en: "Angular blocky",     es: "Bloques angulares",   fr: "Blocs anguleux" }, desc: { pt: "Agregados cúbicos com seis faces planas e arestas agudas. As faces dos blocos encaixam-se entre si. Indica horizonte B com acúmulo de argila por iluviação (horizonte Bt). Permeabilidade moderada; drenagem menos livre que nos agregados granulares.", en: "Cubic aggregates with six flat faces and sharp edges. Block faces fit together. Indicates a B horizon with clay accumulation by illuviation (Bt horizon). Moderate permeability; less free drainage than granular aggregates.", es: "Agregados cúbicos con seis caras planas y aristas agudas. Las caras de los bloques encajan entre sí. Indica horizonte B con acumulación de arcilla por iluviación (horizonte Bt). Permeabilidad moderada; drenaje menos libre que en los agregados granulares.", fr: "Agrégats cubiques avec six faces planes et arêtes vives. Les faces des blocs s'emboîtent. Indique un horizon B avec accumulation d'argile par illuviation (horizon Bt). Perméabilité modérée ; drainage moins libre que les agrégats granulaires." } },
  { value: "subangular_blocky",  label: { pt: "Blocos subangulares", en: "Subangular blocky", es: "Bloques subangulares", fr: "Blocs subanguleux" }, desc: { pt: "Semelhante aos blocos angulares, mas com algumas faces curvas e cantos mistos (parte agudos, parte arredondados). Mais comum em Latossolos e Argissolos do que os blocos angulares. Indica pedogênese moderada a avançada.", en: "Similar to angular blocks but with some curved faces and mixed corners (partly sharp, partly rounded). More common in Latosols and Ultisols than angular blocks. Indicates moderate to advanced pedogenesis.", es: "Similar a los bloques angulares, pero con algunas caras curvas y esquinas mixtas (parte agudas, parte redondeadas). Más común en Latosoles y Ultisoles que los bloques angulares. Indica pedogénesis moderada a avanzada.", fr: "Similaire aux blocs anguleux, mais avec certaines faces courbes et des coins mixtes (partiellement aigus, partiellement arrondis). Plus commun dans les Latosols et Ultisols que les blocs anguleux. Indique une pédogenèse modérée à avancée." } },
  { value: "prismatic",          label: { pt: "Prismática",         en: "Prismatic",          es: "Prismática",          fr: "Prismatique" }, desc: { pt: "Agregados alongados verticalmente com topos planos, formando colunas paralelas entre si. Característico de solos com argilominerais expansivos (montmorilonita) que se expandem e contraem sazonalmente. As faces verticais podem apresentar revestimentos argilosos.", en: "Vertically elongated aggregates with flat tops, forming parallel columns. Characteristic of soils with expansive clay minerals (montmorillonite) that seasonally expand and contract. Vertical faces may show clay coatings.", es: "Agregados elongados verticalmente con topos planos, formando columnas paralelas entre sí. Característico de suelos con arcillominerales expansivos (montmorillonita) que se expanden y contraen estacionalmente. Las caras verticales pueden presentar revestimientos arcillosos.", fr: "Agrégats allongés verticalement avec des sommets plats, formant des colonnes parallèles. Caractéristique des sols avec des minéraux argileux expansifs (montmorillonite) qui se dilatent et se contractent saisonnièrement. Les faces verticales peuvent présenter des revêtements argileux." } },
  { value: "columnar",           label: { pt: "Colunar",            en: "Columnar",           es: "Columnar",            fr: "Columnaire" }, desc: { pt: "Semelhante à prismática, mas com topos arredondados e frequentemente com cobertura branca (sais) ou escura no ápice das colunas. Diagnóstico de solos sódicos com alto teor de sódio trocável. Característico de Vertissolos, Planossolos e Solonetz.", en: "Similar to prismatic but with rounded tops and often with white (salts) or dark coating at the column apex. Diagnostic of sodic soils with high exchangeable sodium content. Characteristic of Vertisols, Planosols, and Solonetz.", es: "Similar a la prismática, pero con topos redondeados y, frecuentemente, con cobertura blanca (sales) o oscura en el ápice de las columnas. Diagnóstico de suelos sódicos con alto contenido de sodio intercambiable. Característico de Vertisoles, Planosoles y Solonetz.", fr: "Similaire au prismatique, mais avec des sommets arrondis et souvent avec un revêtement blanc (sels) ou sombre à l'apex des colonnes. Diagnostic des sols sodiques à haute teneur en sodium échangeable. Caractéristique des Vertisols, Planosols et Solonetz." } },
];

export const crackOptions: SelectOption[] = [
  { value: "absent", label: { pt: "Ausente",            en: "Absent",        es: "Ausente",       fr: "Absent" }, desc: { pt: "Sem fissuras ou rachaduras visíveis na camada. Indica argilominerais de baixa atividade (como a caulinita, predominante em solos tropicais intemperizados), solo com bom conteúdo de água ou textura não argilosa.", en: "No visible cracks or fissures in the layer. Indicates low-activity clay minerals (such as kaolinite, predominant in weathered tropical soils), adequate soil moisture, or non-clayey texture.", es: "Sin fisuras ni grietas visibles en la capa. Indica arcillominerales de baja actividad (como la caolinita, predominante en suelos tropicales meteorizados), buen contenido de agua o textura no arcillosa.", fr: "Sans fissures ni craquelures visibles dans la couche. Indique des argiles à faible activité (comme la kaolinite, prédominante dans les sols tropicaux altérés), une bonne teneur en eau ou une texture non argileuse." } },
  { value: "narrow", label: { pt: "Estreita (< 1 cm)",  en: "Narrow (< 1 cm)", es: "Estrecha (< 1 cm)", fr: "Étroite (< 1 cm)" }, desc: { pt: "Fissuras visíveis com largura inferior a 1 cm. Indica argilominerais com atividade moderada ou solo argiloso em processo inicial de ressecamento. Comum em Argissolos e Cambissolos de textura argilosa durante o período seco.", en: "Visible cracks narrower than 1 cm. Indicates clay minerals with moderate activity or clayey soil in early desiccation. Common in Argisols and Cambisols with clayey texture during the dry season.", es: "Fisuras visibles de menos de 1 cm de ancho. Indica arcillominerales con actividad moderada o suelo arcilloso en proceso inicial de desecación. Común en Argisoles y Cambisoles de textura arcillosa durante la estación seca.", fr: "Fissures visibles de moins de 1 cm de largeur. Indique des argiles à activité modérée ou un sol argileux en début de dessiccation. Commun dans les Argisols et Cambisols à texture argileuse pendant la saison sèche." } },
  { value: "wide",   label: { pt: "Larga (> 1 cm)",     en: "Wide (> 1 cm)", es: "Ancha (> 1 cm)", fr: "Large (> 1 cm)" }, desc: { pt: "Fissuras com largura superior a 1 cm, abertas mesmo com alguma umidade no perfil. Indica argilominerais 2:1 de alta atividade (montmorilonita) com ciclos intensos de expansão e contração sazonal. Diagnóstico de Vertissolos e Planossolos; indica drenagem impedida ou alternante.", en: "Cracks wider than 1 cm, open even with some moisture in the profile. Indicates high-activity 2:1 clay minerals (montmorillonite) with intense seasonal expansion-contraction cycles. Diagnostic of Vertisols and Planosols; indicates impeded or alternating drainage.", es: "Fisuras de más de 1 cm de ancho, abiertas incluso con algo de humedad en el perfil. Indica arcillominerales 2:1 de alta actividad (montmorillonita) con intensos ciclos de expansión y contracción estacional. Diagnóstico de Vertisoles y Planosoles; indica drenaje impedido o alternante.", fr: "Fissures de plus de 1 cm de largeur, ouvertes même avec une certaine humidité dans le profil. Indique des argiles 2:1 à haute activité (montmorillonite) avec des cycles intenses d'expansion-contraction saisonniers. Diagnostique des Vertisols et Planosols ; indique un drainage empêché ou alternant." } },
];

export const coverClassOptions: SelectOption[] = [
  { value: "absent",  label: { pt: "Ausente", en: "Absent",  es: "Ausente", fr: "Absent" } },
  { value: "1-5%",    label: { pt: "1-5%",    en: "1-5%",    es: "1-5%",    fr: "1-5%" } },
  { value: "5-25%",   label: { pt: "5-25%",   en: "5-25%",   es: "5-25%",   fr: "5-25%" } },
  { value: "25-50%",  label: { pt: "25-50%",  en: "25-50%",  es: "25-50%",  fr: "25-50%" } },
  { value: "50-75%",  label: { pt: "50-75%",  en: "50-75%",  es: "50-75%",  fr: "50-75%" } },
  { value: ">75%",    label: { pt: ">75%",    en: ">75%",    es: ">75%",    fr: ">75%" } },
];

/** Fields of ONE soil layer - used both in the schema and in the tests. */
export const soilLayerItemFields: FieldSchema[] = [
  { id: "depth_start",      label: { pt: "Prof. inicial (cm)",  en: "Start depth (cm)",    es: "Prof. inicial (cm)",  fr: "Prof. initiale (cm)" }, type: "text" },
  { id: "depth_end",        label: { pt: "Prof. final (cm)",    en: "End depth (cm)",      es: "Prof. final (cm)",    fr: "Prof. finale (cm)" },   type: "text" },
  { id: "texture",          label: { pt: "Textura",             en: "Texture",             es: "Textura",             fr: "Texture" },             type: "select", options: textureOptions },
  { id: "structure",        label: { pt: "Estrutura",           en: "Structure",           es: "Estructura",          fr: "Structure" },           type: "select", options: structureOptions },
  { id: "color_pattern",    label: { pt: "Padrão de cor",       en: "Color pattern",       es: "Patrón de color",     fr: "Motif de couleur" },    type: "select", options: colorPatternOptions },
  { id: "color_primary",    label: { pt: "Cor primária",        en: "Primary color",       es: "Color primario",      fr: "Couleur primaire" },    type: "select", options: colorTermOptions },
  { id: "color_secondary",  label: { pt: "Cor secundária",      en: "Secondary color",     es: "Color secundario",    fr: "Couleur secondaire" },  type: "select", options: colorTermOptions },
  { id: "cracks",           label: { pt: "Rachaduras",          en: "Cracks",              es: "Grietas",             fr: "Fissures" },            type: "select", options: crackOptions },
  { id: "has_gravel",       label: { pt: "Cascalho",            en: "Gravel",              es: "Grava",               fr: "Graviers" },            type: "boolean", description: { pt: "Presença de fragmentos de rocha com diâmetro superior a 2 mm (cascalhos) ou de pedras na superfície ou interior da camada (pedregosidade). Indica material de origem pedregoso, processo erosivo pretérito que removeu a fração fina, ou herança de material coluvionar.", en: "Presence of rock fragments larger than 2 mm (gravel) or stones on the surface or within the layer. Indicates stony parent material, past erosive processes that removed fine particles, or colluvial material inheritance.", es: "Presencia de fragmentos de roca con diámetro superior a 2 mm (cascajos) o piedras en la superficie o interior de la capa. Indica material de origen pedregoso, procesos erosivos pretéritos que removieron la fracción fina, o herencia de material coluvionar.", fr: "Présence de fragments de roche de diamètre supérieur à 2 mm (graviers) ou de pierres en surface ou dans la couche. Indique un matériau parental pierreux, des processus érosifs passés ayant éliminé la fraction fine, ou un héritage de matériau colluvionnaire." } },
  { id: "has_roots",        label: { pt: "Raízes",              en: "Roots",               es: "Raíces",              fr: "Racines" },             type: "boolean", description: { pt: "Presença de raízes vivas ou mortas na camada analisada. Indica a profundidade efetiva do solo e a atividade biológica do perfil. Raízes em camadas profundas sinalizam boas condições de aeração, ausência de camadas restritivas e solo com profundidade efetiva elevada.", en: "Presence of live or dead roots in the analyzed layer. Indicates the effective soil depth and the biological activity of the profile. Roots in deep layers signal good aeration conditions, absence of restrictive layers, and high effective soil depth.", es: "Presencia de raíces vivas o muertas en la capa analizada. Indica la profundidad efectiva del suelo y la actividad biológica del perfil. Raíces en capas profundas señalan buenas condiciones de aireación, ausencia de capas restrictivas y suelo de elevada profundidad efectiva.", fr: "Présence de racines vivantes ou mortes dans la couche analysée. Indique la profondeur effective du sol et l'activité biologique du profil. Des racines dans les couches profondes signalent de bonnes conditions d'aération, l'absence de couches restrictives et une profondeur effective élevée." } },
  { id: "has_nodules",      label: { pt: "Nódulos",             en: "Nodules",             es: "Nódulos",             fr: "Nodules" },             type: "boolean", description: { pt: "Presença de corpos cimentados de óxido de ferro (goethita, hematita) ou manganês, geralmente de formato arredondado e cor avermelhada a preta. Sinaliza episódios de hidromorfismo passado ou presente, com alternância de condições de oxidação e redução associadas a flutuações do lençol freático.", en: "Presence of cemented bodies of iron oxide (goethite, hematite) or manganese, usually rounded in shape and reddish to black in color. Signals past or present hydromorphism episodes, with alternating oxidizing and reducing conditions associated with water table fluctuations.", es: "Presencia de cuerpos cementados de óxido de hierro (goethita, hematita) o manganeso, generalmente de forma redondeada y color rojizo a negro. Señala episodios de hidromorfismo pasado o presente, con alternancia de condiciones de oxidación y reducción asociadas a fluctuaciones del nivel freático.", fr: "Présence de corps cimentés d'oxyde de fer (goéthite, hématite) ou de manganèse, généralement de forme arrondie et de couleur rougeâtre à noire. Signale des épisodes d'hydromorphie passés ou présents, avec alternance de conditions oxydantes et réductrices associées aux fluctuations de la nappe." } },
  { id: "has_dispersive",   label: { pt: "Dispersivo",          en: "Dispersive",          es: "Dispersivo",          fr: "Dispersif" },           type: "boolean", description: { pt: "Solo com alta concentração de sódio trocável que se dispersa em contato com água pura, formando crosta superficial impermeável e suspensão turva. Indica solo sódico (Solonetz, Planossolo) com alta suscetibilidade à erosão interna por piping e ao encrostamento superficial.", en: "Soil with high exchangeable sodium content that disperses on contact with pure water, forming an impermeable surface crust and a turbid suspension. Indicates sodic soil (Solonetz, Planosol) with high susceptibility to internal erosion by piping and surface crusting.", es: "Suelo con alta concentración de sodio intercambiable que se dispersa en contacto con agua pura, formando costra superficial impermeable y suspensión turbia. Indica suelo sódico (Solonetz, Planossolo) con alta susceptibilidad a la erosión interna por piping y al encostramento superficial.", fr: "Sol à haute teneur en sodium échangeable qui se disperse au contact de l'eau pure, formant une croûte de surface imperméable et une suspension trouble. Indique un sol sodique (Solonetz, Planosol) à haute susceptibilité à l'érosion interne par piping et à la formation de croûtes de surface." } },
  { id: "has_hardened",     label: { pt: "Endurecido",          en: "Hardened",            es: "Endurecido",          fr: "Durci" },               type: "boolean", description: { pt: "Horizonte com consistência muito dura a extremamente dura quando seco, resistente à penetração de raízes e à escavação manual. Pode indicar horizonte coeso (comum no Nordeste brasileiro), fragipã ou horizonte plíntico, restringindo a infiltração de água e o crescimento radicular.", en: "Horizon with very hard to extremely hard consistency when dry, resistant to root penetration and manual excavation. May indicate a cohesive horizon (common in northeastern Brazil), fragipan, or plinthic horizon, restricting water infiltration and root growth.", es: "Horizonte con consistencia muy dura a extremadamente dura cuando seco, resistente a la penetración de raíces y a la excavación manual. Puede indicar horizonte cohesivo (común en el Nordeste brasileño), fragipán u horizonte plíntico, restringiendo la infiltración de agua y el crecimiento radicular.", fr: "Horizon à consistance très dure à extrêmement dure quand sec, résistant à la pénétration des racines et à l'excavation manuelle. Peut indiquer un horizon cohésif (commun dans le Nordeste brésilien), un fragipan ou un horizon plinthique, restreignant l'infiltration de l'eau et la croissance racinaire." } },
  { id: "has_water_table",  label: { pt: "Lençol freático",     en: "Water table",         es: "Nivel freático",      fr: "Nappe phréatique" },    type: "boolean", description: { pt: "Afloramento de água durante a descrição da camada, indicando que o lençol freático está dentro do perfil no momento do levantamento. Evidencia drenagem imperfeita a muito mal drenada, com implicações diretas para a vegetação que pode ser sustentada no sítio e para os processos geossistêmicos locais.", en: "Water seeping into the layer during description, indicating the water table is within the profile at the time of the survey. Evidences imperfect to very poorly drained conditions, with direct implications for the vegetation that can be sustained at the site and for local geosystemic processes.", es: "Afloramiento de agua durante la descripción de la capa, indicando que el nivel freático está dentro del perfil en el momento del levantamiento. Evidencia drenaje imperfecto a muy mal drenado, con implicaciones directas para la vegetación que puede sustentarse en el sitio y para los procesos geosistémicos locales.", fr: "Affleurement d'eau pendant la description de la couche, indiquant que la nappe phréatique est dans le profil au moment du levé. Témoigne d'un drainage imparfait à très mauvais, avec des implications directes pour la végétation pouvant être soutenue sur le site et pour les processus géosystémiques locaux." } },
];

// --- Cover and Surface ---

const surfaceCoverFields: FieldSchema[] = [
  {
    id: "litter_layer", label: { pt: "Serrapilheira", en: "Litter",    es: "Hojarasca",     fr: "Litière" },   type: "select", options: coverClassOptions,
    description: { pt: "restos de folhas, galhos, cascas, frutos e flores caídos no solo", en: "fallen leaves, branches, bark, fruits and flowers on the ground", es: "restos de hojas, ramas, corteza, frutos y flores caídos en el suelo", fr: "feuilles mortes, branches, écorces, fruits et fleurs tombés au sol" },
  },
  {
    id: "stoniness",    label: { pt: "Pedregosidade", en: "Stoniness", es: "Pedregosidad",  fr: "Pierrosité" }, type: "select", options: coverClassOptions,
    description: { pt: "fragmentos de minerais e rochas de 2 a 25cm de diâmetro", en: "fragments of minerals and rocks from 2 to 25cm in diameter", es: "fragmentos de minerales y rocas de 2 a 25cm de diámetro", fr: "fragments de minéraux et de roches de 2 à 25 cm de diamètre" },
  },
  {
    id: "rockiness",    label: { pt: "Rochosidade",   en: "Rockiness", es: "Rocosidad",     fr: "Rochosité" },  type: "select", options: coverClassOptions,
    description: { pt: "afloramentos e fragmentos de rochas e minerais com mais de 25cm de diâmetro", en: "outcrops and fragments of rocks and minerals larger than 25cm in diameter", es: "afloramientos y fragmentos de rocas y minerales mayores a 25cm de diámetro", fr: "affleurements et fragments de roches et minéraux de plus de 25 cm de diamètre" },
  },
  {
    id: "bare_soil",    label: { pt: "Chão exposto",  en: "Bare soil", es: "Suelo desnudo", fr: "Sol nu" },     type: "select", options: coverClassOptions,
    description: { pt: "solo ou regolito sem cobertura", en: "soil or regolith without cover", es: "suelo o regolito sin cobertura", fr: "sol ou régolithe sans couverture" },
  },
];

// --- Soil Description ---

const soilProfileFields: FieldSchema[] = [
  // --- Modo de coleta ---
  {
    id: "mode",
    label: { pt: "Modo de coleta", en: "Collection mode", es: "Modo de recolección", fr: "Mode de collecte" },
    type: "select",
    required: true,
    options: [
      { value: "simple",   label: { pt: "Simples",   en: "Simple",   es: "Simple",   fr: "Simple" } },
      { value: "detailed", label: { pt: "Detalhado", en: "Detailed", es: "Detallado", fr: "Détaillé" } },
    ],
  },

  // --- Modo simples ---
  {
    id: "simple_description",
    label: { pt: "Descrição simplificada (legado)", en: "Simple description (legacy)", es: "Descripción simplificada (heredado)", fr: "Description simplifiée (héritage)" },
    type: "text",
  },
  { id: "simple_color_pattern",   label: { pt: "Padrão de cor (simples)",    en: "Color pattern (simple)",   es: "Patrón de color (simple)",    fr: "Motif de couleur (simple)" },   type: "select", options: colorPatternOptions },
  { id: "simple_color_primary",   label: { pt: "Cor primária (simples)",      en: "Primary color (simple)",   es: "Color primario (simple)",      fr: "Couleur primaire (simple)" },   type: "select", options: colorTermOptions },
  { id: "simple_color_secondary", label: { pt: "Cor secundária (simples)",    en: "Secondary color (simple)", es: "Color secundario (simple)",    fr: "Couleur secondaire (simple)" }, type: "select", options: colorTermOptions },
  { id: "simple_texture",         label: { pt: "Textura (simples)",           en: "Texture (simple)",         es: "Textura (simple)",             fr: "Texture (simple)" },           type: "select", options: textureOptions },
  { id: "simple_structure",       label: { pt: "Estrutura (simples)",         en: "Structure (simple)",       es: "Estructura (simple)",          fr: "Structure (simple)" },         type: "select", options: structureOptions },
  { id: "simple_cracks",          label: { pt: "Rachaduras (simples)",        en: "Cracks (simple)",          es: "Grietas (simple)",             fr: "Fissures (simple)" },          type: "select", options: crackOptions },
  { id: "simple_has_gravel",       label: { pt: "Cascalho (simples)",       en: "Gravel (simple)",       es: "Grava (simple)",       fr: "Graviers (simple)" },       type: "boolean", description: { pt: "Presença de fragmentos de rocha com diâmetro superior a 2 mm (cascalhos) ou de pedras na superfície ou interior da camada (pedregosidade). Indica material de origem pedregoso, processo erosivo pretérito que removeu a fração fina, ou herança de material coluvionar.", en: "Presence of rock fragments larger than 2 mm (gravel) or stones on the surface or within the layer. Indicates stony parent material, past erosive processes that removed fine particles, or colluvial material inheritance.", es: "Presencia de fragmentos de roca con diámetro superior a 2 mm (cascajos) o piedras en la superficie o interior de la capa. Indica material de origen pedregoso, procesos erosivos pretéritos que removieron la fracción fina, o herencia de material coluvionar.", fr: "Présence de fragments de roche de diamètre supérieur à 2 mm (graviers) ou de pierres en surface ou dans la couche. Indique un matériau parental pierreux, des processus érosifs passés ayant éliminé la fraction fine, ou un héritage de matériau colluvionnaire." } },
  { id: "simple_has_roots",        label: { pt: "Raízes (simples)",         en: "Roots (simple)",        es: "Raíces (simple)",       fr: "Racines (simple)" },        type: "boolean", description: { pt: "Presença de raízes vivas ou mortas na camada analisada. Indica a profundidade efetiva do solo e a atividade biológica do perfil. Raízes em camadas profundas sinalizam boas condições de aeração, ausência de camadas restritivas e solo com profundidade efetiva elevada.", en: "Presence of live or dead roots in the analyzed layer. Indicates the effective soil depth and the biological activity of the profile. Roots in deep layers signal good aeration conditions, absence of restrictive layers, and high effective soil depth.", es: "Presencia de raíces vivas o muertas en la capa analizada. Indica la profundidad efectiva del suelo y la actividad biológica del perfil. Raíces en capas profundas señalan buenas condiciones de aireación, ausencia de capas restrictivas y suelo de elevada profundidad efectiva.", fr: "Présence de racines vivantes ou mortes dans la couche analysée. Indique la profondeur effective du sol et l'activité biologique du profil. Des racines dans les couches profondes signalent de bonnes conditions d'aération, l'absence de couches restrictives et une profondeur effective élevée." } },
  { id: "simple_has_nodules",      label: { pt: "Nódulos (simples)",        en: "Nodules (simple)",      es: "Nódulos (simple)",      fr: "Nodules (simple)" },        type: "boolean", description: { pt: "Presença de corpos cimentados de óxido de ferro (goethita, hematita) ou manganês, geralmente de formato arredondado e cor avermelhada a preta. Sinaliza episódios de hidromorfismo passado ou presente, com alternância de condições de oxidação e redução associadas a flutuações do lençol freático.", en: "Presence of cemented bodies of iron oxide (goethite, hematite) or manganese, usually rounded in shape and reddish to black in color. Signals past or present hydromorphism episodes, with alternating oxidizing and reducing conditions associated with water table fluctuations.", es: "Presencia de cuerpos cementados de óxido de hierro (goethita, hematita) o manganeso, generalmente de forma redondeada y color rojizo a negro. Señala episodios de hidromorfismo pasado o presente, con alternancia de condiciones de oxidación y reducción asociadas a fluctuaciones del nivel freático.", fr: "Présence de corps cimentés d'oxyde de fer (goéthite, hématite) ou de manganèse, généralement de forme arrondie et de couleur rougeâtre à noire. Signale des épisodes d'hydromorphie passés ou présents, avec alternance de conditions oxydantes et réductrices associées aux fluctuations de la nappe." } },
  { id: "simple_has_dispersive",   label: { pt: "Dispersivo (simples)",     en: "Dispersive (simple)",   es: "Dispersivo (simple)",   fr: "Dispersif (simple)" },      type: "boolean", description: { pt: "Solo com alta concentração de sódio trocável que se dispersa em contato com água pura, formando crosta superficial impermeável e suspensão turva. Indica solo sódico (Solonetz, Planossolo) com alta suscetibilidade à erosão interna por piping e ao encrostamento superficial.", en: "Soil with high exchangeable sodium content that disperses on contact with pure water, forming an impermeable surface crust and a turbid suspension. Indicates sodic soil (Solonetz, Planosol) with high susceptibility to internal erosion by piping and surface crusting.", es: "Suelo con alta concentración de sodio intercambiable que se dispersa en contacto con agua pura, formando costra superficial impermeable y suspensión turbia. Indica suelo sódico (Solonetz, Planossolo) con alta susceptibilidad a la erosión interna por piping y al encostramento superficial.", fr: "Sol à haute teneur en sodium échangeable qui se disperse au contact de l'eau pure, formant une croûte de surface imperméable et une suspension trouble. Indique un sol sodique (Solonetz, Planosol) à haute susceptibilité à l'érosion interne par piping et à la formation de croûtes de surface." } },
  { id: "simple_has_hardened",     label: { pt: "Endurecido (simples)",     en: "Hardened (simple)",     es: "Endurecido (simple)",   fr: "Durci (simple)" },          type: "boolean", description: { pt: "Horizonte com consistência muito dura a extremamente dura quando seco, resistente à penetração de raízes e à escavação manual. Pode indicar horizonte coeso (comum no Nordeste brasileiro), fragipã ou horizonte plíntico, restringindo a infiltração de água e o crescimento radicular.", en: "Horizon with very hard to extremely hard consistency when dry, resistant to root penetration and manual excavation. May indicate a cohesive horizon (common in northeastern Brazil), fragipan, or plinthic horizon, restricting water infiltration and root growth.", es: "Horizonte con consistencia muy dura a extremadamente dura cuando seco, resistente a la penetración de raíces y a la excavación manual. Puede indicar horizonte cohesivo (común en el Nordeste brasileño), fragipán u horizonte plíntico, restringiendo la infiltración de agua y el crecimiento radicular.", fr: "Horizon à consistance très dure à extrêmement dure quand sec, résistant à la pénétration des racines et à l'excavation manuelle. Peut indiquer un horizon cohésif (commun dans le Nordeste brésilien), un fragipan ou un horizon plinthique, restreignant l'infiltration de l'eau et la croissance racinaire." } },
  { id: "simple_has_water_table",  label: { pt: "Lençol freático (simples)", en: "Water table (simple)", es: "Nivel freático (simple)", fr: "Nappe phréatique (simple)" }, type: "boolean", description: { pt: "Afloramento de água durante a descrição da camada, indicando que o lençol freático está dentro do perfil no momento do levantamento. Evidencia drenagem imperfeita a muito mal drenada, com implicações diretas para a vegetação que pode ser sustentada no sítio e para os processos geossistêmicos locais.", en: "Water seeping into the layer during description, indicating the water table is within the profile at the time of the survey. Evidences imperfect to very poorly drained conditions, with direct implications for the vegetation that can be sustained at the site and for local geosystemic processes.", es: "Afloramiento de agua durante la descripción de la capa, indicando que el nivel freático está dentro del perfil en el momento del levantamiento. Evidencia drenaje imperfecto a muy mal drenado, con implicaciones directas para la vegetación que puede sustentarse en el sitio y para los procesos geosistémicos locales.", fr: "Affleurement d'eau pendant la description de la couche, indiquant que la nappe phréatique est dans le profil au moment du levé. Témoigne d'un drainage imparfait à très mauvais, avec des implications directes pour la végétation pouvant être soutenue sur le site et pour les processus géosystémiques locaux." } },
  { id: "simple_registered",       label: { pt: "Descrição simples registrada", en: "Simple description registered", es: "Descripción simple registrada", fr: "Description simple enregistrée" }, type: "boolean" },
];

// Order: Cover and Surface (direct observation) → Geomorphology and Relief
// (more analytical reading) → Soil Description (the most operational,
// done last when the profile pit is opened) - ordering decision confirmed
// during design review.
export const geoecologicalConstraintsSchema: ModuleSchema = {
  fields: [...surfaceCoverFields, ...geomorphologyFields, ...soilProfileFields],
  dynamic: [
    {
      groupId: "soil_layers",
      itemFields: soilLayerItemFields,
      columnNamePattern: "soil_layer_{i}_{field}",
    },
  ],
};
