import type { PointColumnDef } from "@/core/export/generic-export-engine";

// Point-level columns exclusive to PAISAGEO (name generated by Kuchler
// classification, landscape class id, parcel size) - they don't make sense
// in custom protocols, so they're declared here rather than in the generic
// engine (core/export/generic-export-engine.ts).
//
// Extracted into its own file (without depending on db/queries/*) so the
// tests in core/export/__tests__/generic-export-engine.test.ts can import
// this list without dragging in db/initialize.ts (expo-sqlite), which the
// test runner (ts-jest + plain node, see jest.config.js) can't transform.
export const EXTRA_POINT_COLUMNS: PointColumnDef[] = [
  { key: "generated_name", label: "generated_name", getValue: (p) => p.generatedName ?? null },
  { key: "landscape_class_id", label: "landscape_class_id", getValue: (p) => p.landscapeClassId ?? null },
  { key: "point_size", label: "point_size", getValue: (p) => p.pointSize ?? null },
];
