import vegetationClasses from '@/assets/protocols/paisageo/vegetation_classes.json';

// --- CONSTANTS ---

// Structurally dominant life forms (determine class C1–C4)
// C (Liana) and X (Epiphyte) are Special but NEVER structurally dominant
const WOODY_FORMS = new Set(['B', 'D', 'E', 'N', 'O', 'S', 'M', 'K', 'T', 'V']);
const HERB_FORMS  = new Set(['G', 'H', 'L']);

const COVER_RANK: Record<string, number> = { c: 6, i: 5, p: 4, r: 3, b: 2 };

// --- TYPES ---

export interface StratumComponent {
  heightClass: number;
  lifeForm: string;
  leafAdaptation?: string;
  coverClass: string;
  coverValue: number;
}

export interface ClassificationResult {
  code: string;
  groupCode: string;
  name: string;
  groupName: string;
}

// Internal grouping of all strata belonging to one life form
interface LifeFormGroup {
  code: string;
  leafAdaptation?: string;
  strata: { height: number; coverRank: number; coverClass: string }[];
  isWoody: boolean;
  isHerb: boolean;
  domCovRank: number; // max coverage rank across all strata
  maxHeight: number;  // max height across all strata
}

// Context flags for types that are not derivable from the formula alone
export type ContextFlag = 'mangrove' | 'spiny' | 'semi-lignified';

// --- HELPERS ---

const getCoverRank = (ch: string): number => COVER_RANK[ch.toLowerCase()] ?? 0;
const padT = (n: number): string => n.toString().padStart(2, '0');

// --- PARSER ---

/**
 * Parses a raw Küchler formula into flat stratum components.
 * Raw format generated by kuchler-formula.ts:
 *   Each entry: [LifeForm][LeafAdaptation?][Height][Cover]  e.g. "Bh6i"
 *   Same-height entries separated by ","  |  different heights separated by "."
 *
 * Leaf adaptation letters: h w k l s (appear BEFORE the height digit)
 * Cover class letters: c i p r b a (appear AFTER the height digit)
 */
export const parseRawFormula = (rawFormula: string): StratumComponent[] => {
  if (!rawFormula) return [];

  const components: StratumComponent[] = [];
  // Leaf letters restricted to {h,w,k,l,s} to avoid ambiguity with cover letters
  const regex = /^([A-Z])([hwkls]?)([1-8])([ciprb])$/;

  for (const part of rawFormula.split(/[.,]/)) {
    const m = part.match(regex);
    if (m) {
      const coverClass = m[4];
      components.push({
        lifeForm:       m[1],
        leafAdaptation: m[2] || undefined,
        heightClass:    parseInt(m[3], 10),
        coverClass,
        coverValue:     getCoverRank(coverClass),
      });
    }
  }

  return components.sort((a, b) =>
    b.heightClass !== a.heightClass
      ? b.heightClass - a.heightClass
      : b.coverValue  - a.coverValue
  );
};

// --- GROUP BY LIFE FORM ---

function groupByLifeForm(components: StratumComponent[]): LifeFormGroup[] {
  const map = new Map<string, LifeFormGroup>();

  for (const c of components) {
    // Lianas (C) and Epiphytes (X) are never structurally dominant — skip for classification
    if (c.lifeForm === 'C' || c.lifeForm === 'X') continue;

    if (!map.has(c.lifeForm)) {
      map.set(c.lifeForm, {
        code:           c.lifeForm,
        leafAdaptation: c.leafAdaptation,
        strata:         [],
        isWoody:        WOODY_FORMS.has(c.lifeForm),
        isHerb:         HERB_FORMS.has(c.lifeForm),
        domCovRank:     0,
        maxHeight:      0,
      });
    }

    const g = map.get(c.lifeForm)!;
    g.strata.push({ height: c.heightClass, coverRank: c.coverValue, coverClass: c.coverClass });
    g.domCovRank = Math.max(g.domCovRank, c.coverValue);
    g.maxHeight  = Math.max(g.maxHeight,  c.heightClass);
    if (c.leafAdaptation && !g.leafAdaptation) {
      g.leafAdaptation = c.leafAdaptation;
    }
  }

  return Array.from(map.values());
}

// --- DOMINANT GROUP ---

/**
 * Returns the structurally dominant life form group following the spec dominance rule:
 *   1. Highest coverage rank
 *   2. Tie → highest max height
 *   3. Tie → woody beats herbaceous
 */
function getDominantGroup(groups: LifeFormGroup[]): LifeFormGroup | undefined {
  if (groups.length === 0) return undefined;
  return groups.reduce((best, curr) => {
    if (curr.domCovRank !== best.domCovRank)
      return curr.domCovRank > best.domCovRank ? curr : best;
    if (curr.maxHeight !== best.maxHeight)
      return curr.maxHeight > best.maxHeight ? curr : best;
    if (curr.isWoody !== best.isWoody)
      return curr.isWoody ? curr : best;
    return best;
  });
}

// --- CLASS DETERMINATION (C1–C5) ---

function getVegClass(dominant: LifeFormGroup, allGroups: LifeFormGroup[]): string {
  // Herbaceous dominant → C5
  if (dominant.isHerb) return 'C5';

  // C5 override: herb ≥ p AND all woody ≤ p
  const herbGroups  = allGroups.filter(g => g.isHerb);
  const woodyGroups = allGroups.filter(g => g.isWoody);

  if (herbGroups.length > 0) {
    const bestHerb  = Math.max(...herbGroups.map(g => g.domCovRank));
    const bestWoody = woodyGroups.length > 0
      ? Math.max(...woodyGroups.map(g => g.domCovRank))
      : 0;
    if (bestHerb >= COVER_RANK['p'] && bestWoody <= COVER_RANK['p']) return 'C5';
  }

  // Woody dominant → class by height + coverage
  const h   = dominant.maxHeight;
  const cov = dominant.domCovRank;

  if (h >= 5) return cov >= COVER_RANK['c'] ? 'C1' : 'C2';
  if (h >= 3) return 'C3';
  return 'C4';
}

// --- TYPE DETERMINATION PER CLASS ---

function getC1Type(dom: LifeFormGroup, flags: Set<ContextFlag>): string {
  const { code: lf, leafAdaptation: leaf } = dom;

  if (flags.has('mangrove')) return 'C1_T05';

  if (lf === 'B') {
    if (leaf === 's') return 'C1_T02';
    if (leaf === 'h') return 'C1_T12'; // evergreen sclerophyllous
    return 'C1_T01';
  }
  if (lf === 'E') return 'C1_T03';
  if (lf === 'V') return 'C1_T04';
  if (lf === 'T') return 'C1_T06';
  if (lf === 'S') return 'C1_T07';
  if (lf === 'M') return 'C1_T08';
  if (lf === 'D') {
    if (leaf === 's') return 'C1_T10';
    if (leaf === 'h') return 'C1_T12';
    if (flags.has('spiny')) return 'C1_T13';
    return 'C1_T09';
  }
  if (lf === 'N') return 'C1_T11';
  if (lf === 'K') return 'C1_T14';
  return 'C1_T01'; // O (Aphyllous) and others → broadleaf fallback
}

function getC2Type(dom: LifeFormGroup, flags: Set<ContextFlag>): string {
  const { code: lf, leafAdaptation: leaf } = dom;

  if (lf === 'B') {
    if (leaf === 's') return 'C2_T02';
    if (leaf === 'h') return 'C2_T11'; // open evergreen sclerophyllous
    return 'C2_T01';
  }
  if (lf === 'E') return 'C2_T03';
  if (lf === 'V') return 'C2_T04';
  if (lf === 'T') return 'C2_T05';
  if (lf === 'S') return 'C2_T06';
  if (lf === 'M') return 'C2_T07';
  if (lf === 'D') {
    if (leaf === 's') return 'C2_T09';
    if (leaf === 'h') return 'C2_T11';
    if (flags.has('spiny')) return 'C2_T12';
    return 'C2_T08';
  }
  if (lf === 'N') return 'C2_T10';
  if (lf === 'K') return 'C2_T13';
  return 'C2_T01';
}

function getC3Type(
  dom: LifeFormGroup,
  allGroups: LifeFormGroup[],
  flags: Set<ContextFlag>,
): string {
  const { code: lf, leafAdaptation: leaf, domCovRank } = dom;

  // Subarbustal: only determinable with external flag
  if (flags.has('semi-lignified')) {
    return domCovRank >= COVER_RANK['c'] ? 'C3_T04' : 'C3_T16';
  }

  const isDense  = domCovRank >= COVER_RANK['c'];
  const offset   = isDense ? 0 : 12; // T01–T12 = dense; T13–T24 = open

  // K exception (open subgroup only): if K is present at height 3–4 with cov ≥ p,
  // the succulent type takes over the open arbustal classification.
  if (!isDense && lf !== 'K') {
    const kGroup = allGroups.find(g => g.code === 'K');
    if (kGroup) {
      const kAt34 = kGroup.strata.some(
        s => s.height >= 3 && s.height <= 4 && s.coverRank >= COVER_RANK['p']
      );
      if (kAt34) return 'C3_T24';
    }
  }

  let baseType = 0;
  if (lf === 'B') {
    if (leaf === 'h') baseType = 2;        // sclerophyllous
    else if (leaf === 's') baseType = 3;   // microphyllous
    else baseType = 1;
  }
  else if (lf === 'E') baseType = 5;
  else if (lf === 'T') baseType = 6;
  else if (lf === 'V') baseType = 7;
  else if (lf === 'S') baseType = 8;
  else if (lf === 'M') baseType = 8;       // Mixed → mapped to semi-deciduous in C3
  else if (lf === 'D') baseType = leaf === 's' ? 10 : 9;
  else if (lf === 'N') baseType = 11;
  else if (lf === 'K') baseType = 12;
  else baseType = 1;                        // O (Aphyllous) and others → fallback

  return `C3_T${padT(baseType + offset)}`;
}

function getC4Type(dom: LifeFormGroup, allGroups: LifeFormGroup[]): string {
  const { code: lf, domCovRank } = dom;

  if (lf === 'K') return 'C4_T07';

  // Herbaceous significance: any herb group with cov ≥ p at height 1–2
  const herbCovRank = Math.max(
    0,
    ...allGroups
      .filter(g => g.isHerb)
      .map(g => g.domCovRank)
  );
  const herbSignificant = herbCovRank >= COVER_RANK['p'];
  const dense = domCovRank >= COVER_RANK['c'];

  if (lf === 'B') {
    if (dense) return 'C4_T01';
    return herbSignificant ? 'C4_T03' : 'C4_T02';
  }
  if (lf === 'D') {
    if (dense) return 'C4_T04';
    return herbSignificant ? 'C4_T06' : 'C4_T05';
  }

  // E, N, O, S, M, T, V: the C4 catalog has no life-form-level distinction
  // beyond B/D/K, so these fall into the same "sempreverde" family already
  // used as the "O and others" fallback in C1/C2/C3, but now respecting the
  // actual cover instead of always assuming dense (see classificacao_vegetacao.md §6).
  if (dense) return 'C4_T01';
  return herbSignificant ? 'C4_T03' : 'C4_T02';
}

/**
 * Finds the first associated woody life form in priority order B > S > D > T.
 * For B/S/D: minimum threshold b (rank 2), only strata at height ≥ 3.
 * For T: same threshold, but no synusia/elements distinction (single type per height band).
 * Returns null if no qualifying associated woody is present.
 */
function findC5Associated(
  allGroups: LifeFormGroup[],
  domCode: string,
): { group: LifeFormGroup; covRank: number } | null {
  const THRESHOLD = COVER_RANK['b']; // any non-absent presence qualifies
  const priority  = ['B', 'S', 'D', 'T'] as const;

  for (const wcode of priority) {
    if (wcode === domCode) continue;
    const wg = allGroups.find(g => g.code === wcode);
    if (!wg) continue;

    // Only strata at height ≥ 3 count as associated in C5 context
    const validCovRank = Math.max(
      0,
      ...wg.strata.filter(s => s.height >= 3).map(s => s.coverRank)
    );
    if (validCovRank >= THRESHOLD) {
      return { group: wg, covRank: validCovRank };
    }
  }
  return null;
}

function getC5Type(dom: LifeFormGroup, allGroups: LifeFormGroup[]): string {
  const { code: lf, maxHeight } = dom;

  if (lf === 'L') return 'C5_T39';

  const assoc = findC5Associated(allGroups, lf);

  // --- G (Graminoid): three height bands ---
  if (lf === 'G') {
    const hBand = maxHeight >= 4 ? 1 : maxHeight === 3 ? 2 : 3; // tall/medium/short

    if (!assoc) return `C5_T${padT(hBand)}`; // T01, T02, T03

    if (assoc.group.code === 'T') {
      return `C5_T${padT(21 + hBand)}`; // T22, T23, T24
    }

    // B, S, D: distinguish synusia (≥ p) vs elements (r or b)
    const wIdx     = ['B', 'S', 'D'].indexOf(assoc.group.code);
    const covOff   = assoc.covRank >= COVER_RANK['p'] ? 0 : 1;
    const idx      = 4 + wIdx * 6 + (hBand - 1) * 2 + covOff;
    return `C5_T${padT(idx)}`;
  }

  // --- H (Broadleaf herbaceous): two height bands ---
  if (lf === 'H') {
    const hBand = maxHeight >= 3 ? 1 : 2; // tall (≥3) / short (≤2)

    if (!assoc) return `C5_T${padT(24 + hBand)}`; // T25, T26

    // T (Palm) is not used as associated for H communities (no H+palm types)
    const wIdx = ['B', 'S', 'D'].indexOf(assoc.group.code);
    if (wIdx < 0) return `C5_T${padT(24 + hBand)}`; // T only → pure

    const covOff = assoc.covRank >= COVER_RANK['p'] ? 0 : 1;
    const idx    = 27 + wIdx * 4 + (hBand - 1) * 2 + covOff;
    return `C5_T${padT(idx)}`;
  }

  return 'C5_T01'; // fallback
}

// --- MAIN CLASSIFICATION FUNCTION ---

export const classifyVegetation = (
  rawFormula: string,
  lang: 'pt' | 'en' | 'es' | 'fr' = 'pt',
  contextFlags: ContextFlag[] = [],
): ClassificationResult => {
  const NOT_CLASSIFIED = {
    code:      'NR',
    groupCode: 'NR',
    name:      lang === 'pt' ? 'Não Classificado'
             : lang === 'es' ? 'No Clasificado'
             : lang === 'fr' ? 'Végétation non classifiée'
             : 'Not Classified',
    groupName: '',
  };

  const components = parseRawFormula(rawFormula);
  if (components.length === 0) return NOT_CLASSIFIED;

  const groups   = groupByLifeForm(components);
  const dominant = getDominantGroup(groups);
  if (!dominant) return NOT_CLASSIFIED;

  const flags    = new Set(contextFlags);
  const groupCode = getVegClass(dominant, groups);

  let typeCode = '';
  if      (groupCode === 'C1') typeCode = getC1Type(dominant, flags);
  else if (groupCode === 'C2') typeCode = getC2Type(dominant, flags);
  else if (groupCode === 'C3') typeCode = getC3Type(dominant, groups, flags);
  else if (groupCode === 'C4') typeCode = getC4Type(dominant, groups);
  else if (groupCode === 'C5') typeCode = getC5Type(dominant, groups);

  // @ts-ignore
  const groups_data = vegetationClasses.groups;
  // @ts-ignore
  const types_data  = vegetationClasses.types;

  // @ts-ignore
  const groupName = groups_data[groupCode]?.name[lang] || groupCode;
  // @ts-ignore
  const typeName  = types_data[typeCode]?.[lang] || typeCode || groupName;

  return {
    code:      typeCode || groupCode,
    groupCode,
    name:      typeName,
    groupName,
  };
};

// --- CONTEXT FLAG ELIGIBILITY ---

/**
 * Which context flags would actually affect the classification of the
 * current matrix state. Mirrors the exact conditions checked inside
 * getC1Type/getC2Type/getC3Type above - used by the UI to disable a flag's
 * checkbox when marking it would have no effect (see schema.ts option
 * `desc` for the same conditions in prose).
 */
export function getEligibleContextFlags(rawFormula: string): Set<ContextFlag> {
  const components = parseRawFormula(rawFormula);
  if (components.length === 0) return new Set();

  const groups = groupByLifeForm(components);
  const dominant = getDominantGroup(groups);
  if (!dominant) return new Set();

  const groupCode = getVegClass(dominant, groups);

  const eligible = new Set<ContextFlag>();
  if (groupCode === 'C1') eligible.add('mangrove');
  if (
    dominant.code === 'D' &&
    dominant.leafAdaptation !== 's' &&
    dominant.leafAdaptation !== 'h' &&
    (groupCode === 'C1' || groupCode === 'C2')
  ) {
    eligible.add('spiny');
  }
  if (groupCode === 'C3') eligible.add('semi-lignified');

  return eligible;
}
